logging:
  level:
    com.galasports: debug
    com.galasports.server.dao: warn
server:
  port: 9001
  tomcat:
    uri-encoding: utf-8
    max-threads: 100
spring:
#  resources:
#    static-locations: classpath:/content/
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
#  profiles:
#    active: dev
  devtools:
    restart:
      enabled: true
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    #    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/music?useUnicode=true&characterEncoding=utf8
#    username: root
#    password: KH*&6kdgl3
#    initialSize: 1
#    minIdle: 3
#    maxActive: 20
#    # 配置获取连接等待超时的时间
#    maxWait: 60000
#    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#    timeBetweenEvictionRunsMillis: 60000
#    # 配置一个连接在池中最小生存的时间，单位是毫秒
#    minEvictableIdleTimeMillis: 30000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxPoolPreparedStatementPerConnectionSize: 20
#    filters: stat,wall,slf4j
#    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapperLocations: classpath:mappers/*.xml
